export {default as promiseThen} from "./then/then"
export {default as promiseDelay} from "./delay/delay"
export {default as promiseRetry} from "./retry/retry"
export {default as promiseAllObject} from "./allObject/allObject"
export {default as promiseAllMap} from "./allMap/allMap"

export {default as log} from "./prototype/log/log"
export {default as delay} from "./prototype/delay/delay"
export {default as retry} from "./prototype/retry/retry"
export {default as resolve} from "./prototype/resolve/resolve"
export {default as reject} from "./prototype/reject/reject"
export {default as all} from "./prototype/all/all"
export {default as allSettled} from "./prototype/allSettled/allSettled"
export {default as allObject} from "./prototype/allObject/allObject"