import './then';
import './delay';
import './retry';
import './allWith';
import './timeOut';
import './wrap';
import './sequence';
import './reduce';

import './prototype/log';
import './prototype/delay';
import './prototype/retry';
import './prototype/resolve';
import './prototype/reject';
import './prototype/all';
import './prototype/allSettled';
import './prototype/timeOut';
import './prototype/wrap';
import './prototype/sequence';